name: zxing_dart
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Eastonboy99 <tyler@gwins.net>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  fixnum: ^0.10.9
  collection: any
  built_value: ^6.7.1
  image: ^2.1.9

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0